"""
Perform Monte Carlo simulation with the SRH_2D_Model and SRH_2D_Data classes. It uses pyHMT2D to control the run of SRH-2D model, extract information, and parallelization.

The parameter values for the Monte Carlo simulation are read in from a file, which should be generated by the preprocessing script.
"""

#if run in the cloud, need to specify the location of pyHMT2D. If pyHMT2D is installed
#with regular pip install, then the following is not necessary.
#import sys
#sys.path.append(r"C:\Users\Administrator\python_packages\pyHMT2D")

import pyHMT2D

import numpy as np

import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter

import multiprocessing
import os
import sys
import json
import platform
import time
from datetime import datetime

# Set the random seed before generating any random numbers
np.random.seed(123456)  # You can use any integer as the seed

# Add the SRH_2D_automation directory to Python path (adjust this path as needed)
root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../"))
sys.path.append(root_dir)

# Now import the SRH_2D_solver_module 
from SRH_2D_solver_module import run_one_SRH_2D_case

plt.rc('text', usetex=False)  #allow the use of Latex for math expressions and equations
plt.rc('font', family='serif') #specify the default font family to be "serif"


def Monte_Carlo_simulations_parallel(srhcontrol_file, samples, ManningN_MaterialID, ManningN_MaterialName, Q_bc_ID, WSE_bc_ID, system_name, nProcess, bDeleteCaseDir=True):
    """
    Run Monte Carlo simulations nSamples times. Run all cases in parallel using multiple CPU cores. Each core
    simulates one case at a time.

    In this example, only one inlet-q and one Manning's n is varied for a zone in the domain. For the exit-h boundary, a rating curve is used. Thus, there is no need to change anything for the exit-h boundary.

    Parameters
    ----------
    srhcontrol_file : str
        Name of the SRH-2D control file (either srhhydro or SIF file), e.g., "case_SIF.dat" or "case.srhhydro"
    samples : numpy array
        list of Manning's n values
    ManningN_MaterialID : int
        ID of the Manning's n zone. Note: in HEC-RAS, the ID is 1-based.
    ManningN_MaterialName : str
        Name of the Manning's n zone
    Q_bc_ID : int
        ID of the inlet boundary 
    WSE_bc_ID : int (no need for this example)
        ID of the outlet boundary 
    system_name : str
        Name of the operating system, e.g., "Windows" or "Linux"
    nProcess : int
        number of parallel processes to use
    bDeleteCaseDir : bool
        whether to delete case directory when simulation is done. Default is True. If it is set to False, the case directory
        will be kept. However, be cautious on this. If the number of simulations is large, all cases together will use
        very large space on the hard disk.

        In this example, the simulation result is saved into a VTK file (thus the case directory is not needed after
        simulation is done).

    Returns
    -------

    """

    #print("Running Monte Carlo simulations in parallel with", nProcess, "processes ...")

    #number of samples
    nSamples = samples.shape[0]

    #access the parameter values
    Manning_n_samples = samples['Manning_n']
    Q_samples = samples['Q']
    WSE_samples = samples['WSE']

    #create a pool of parallel workers
    pool = multiprocessing.Pool(processes=nProcess)

    #make the directory "cases". If it already exists, reminder user that the contents within may be overwritten.
    if os.path.isdir("cases"):
        print("The directory cases already exists. The contents within may be overwritten.")
        #quit()
    else:
        os.mkdir("cases")

    #create the list of case IDs to be assigned to the parallel workers
    caseIDs = [*range(1, nSamples+1, 1)]    

    #prepare the arguments for calling the "run_one_SRH_2D_case(...)" function
    #args: case_ID, srhcontrol_file, ManningN_MaterialID, ManningN, ManningN_MaterialName, Q_bc_ID, Q,  WSE_bc_ID, WSE, system_name
    args = [(caseID, srhcontrol_file, ManningN_MaterialID, ManningN, ManningN_MaterialName, Q_bc_ID, Q, WSE_bc_ID, WSE, system_name, bDeleteCaseDir) 
            for caseID, ManningN, Q, WSE in zip(caseIDs, Manning_n_samples, Q_samples, WSE_samples)]
    
    #optional or for debugging: only run a subset of cases 
    #args = args[:10]  #only run the first 10 cases 
    #args = args[0:1000]  #only run the first 1000 cases
    #args = args[1000:2000]  #only run the first cases 1000 to 1999
    #args = args[50, 51, 108, 99]  #only run the first cases in the list

    #print("args = ", args)

    # do the work
    outputs = pool.starmap(run_one_SRH_2D_case, args)    

    print("Parallel run of cases done.")

    # Count the number of successful and failed runs
    successful_runs = [output for output in outputs if output > 0]
    failed_runs = [output for output in outputs if output < 0]
    print("    Number of successful runs = ", len(successful_runs))
    print("    Number of failed runs = ", len(failed_runs))

    # save the returned outputs as a json file: outputs contains the caseIDs (positive if the case run was successful,
    # negative otherwise); also save successful and failed runs in the same json file
    # prepare the data to be saved
    date_time = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")    #take the current date and time
    output_filename = f'parallel_run_SRH_2D_outputs_{date_time}.json'
    data_to_save = {
        "nSamples": nSamples,
        "nSamples_successful": len(successful_runs),
        "nSamples_failed": len(failed_runs),
        "all_run_results": outputs,
        "successful_runs": successful_runs,
        "failed_runs": failed_runs
    }
    with open(output_filename, 'w') as f:
        json.dump(data_to_save, f, indent=4)

def Monte_Carlo_simulations_serial(srhcontrol_file, samples, ManningN_MaterialID, ManningN_MaterialName, Q_bc_ID, WSE_bc_ID, system_name, bDeleteCaseDir=True):
    """
    Run Monte Carlo simulations in serial

    Parameters
    ----------
    srhcontrol_file : str
        Name of the SRH-2D control file (either srhhydro or SIF file), e.g., "case_SIF.dat" or "case.srhhydro"
    samples : numpy array
        list of parameter values
    ManningN_MaterialID : int

        ID of the Manning's n zone. Note: in SRH-2D, the ID is 1-based.
    ManningN_MaterialName : str
        Name of the Manning's n zone
    Q_bc_ID : int
        ID of the inlet boundary 
    WSE_bc_ID : int
        ID of the outlet boundary 
    bDeleteCaseDir : bool
        whether to delete case directory when simulation is done. Default is True. If it is set to False, the case directory
        will be kept. However, be cautious on this. If the number of simulations is large, all cases together will use
        very large space on the hard disk.

        In this example, the SRH-2D result is saved into a VTK file (thus the case directory is not needed after
        simulation is done).

    Returns
    -------

    """

    print("Running Monte Carlo simulations in serial ...")

    #number of samples
    nSamples = samples.shape[0]

    #access the parameter values
    Manning_n_samples = samples['Manning_n']
    Q_samples = samples['Q']
    WSE_samples = samples['WSE']

    #make the directory "cases". If it already exists, reminder user that the contents within may be overwritten.
    if os.path.isdir("cases"):
        print("The directory cases already exists. The contents within may be overwritten.")
        #quit()
    else:
        os.mkdir("cases")

    #list to collect outputs
    outputs = []

    #for i in range(1, nSamples+1):   #run all cases in the sample file (case ID starts from 1)
    for i in range(1, 3):  #For debugging/testing, only run the first 3 cases
        print("    Running Monte Carlo simulation # ", i, "out of", nSamples)

        #access the parameter values
        ManningN = Manning_n_samples[i]
        Q = Q_samples[i]
        WSE = WSE_samples[i]

        print("ManningN = ", ManningN)
        print("Q = ", Q)
        print("WSE = ", WSE)

        output = run_one_SRH_2D_case(i, srhcontrol_file, ManningN_MaterialID, ManningN, ManningN_MaterialName, Q_bc_ID, Q, WSE_bc_ID, WSE, system_name, bDeleteCaseDir)


        outputs.append(output)
    
    print("    Serial run of cases done.")    

    # Count the number of successful and failed runs
    successful_runs = [output for output in outputs if output > 0]
    failed_runs = [output for output in outputs if output < 0]
    print("    Number of successful runs = ", len(successful_runs))
    print("    Number of failed runs = ", len(failed_runs))

    # save the returned outputs as a json file: outputs contains the caseIDs (positive if the case run was successful,
    # negative otherwise); also save successful and failed runs in the same json file
    # prepare the data to be saved
    date_time = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")    #take the current date and time
    output_filename = f'serial_run_SRH_2D_outputs_{date_time}.json'
    data_to_save = {
        "nSamples": nSamples,
        "nSamples_successful": len(successful_runs),
        "nSamples_failed": len(failed_runs),
        "all_run_results": outputs,
        "successful_runs": successful_runs,
        "failed_runs": failed_runs
    }
    with open(output_filename, 'w') as f:
        json.dump(data_to_save, f, indent=4)

if __name__ == "__main__":

    #record the start time
    start_time = time.time()

    #read the run specs from the json config file
    print("Reading the configuration file ...")
    with open('simulations_config.json', 'r') as f:
        config = json.load(f)

    run_specs = config['run_specs']

    #The name of the case (used as the base to generate other file names, such as the control file name)
    case_name = run_specs['case_name']
    
    #The name of the file containing the sampled parameters
    sampled_parameters_file = run_specs['sampled_parameters_file']
    
    #The ID of the Manning's n zone whose n value is changes in the Monte Carlo simulations. If ManningN_MaterialID does not exist, it is set to -1.
    ManningN_MaterialID = -1
    if 'ManningN_MaterialID' in run_specs:
        ManningN_MaterialID = run_specs['ManningN_MaterialID']

    #make sure ManningN_MaterialID is a valid integer
    if not isinstance(ManningN_MaterialID, int):
        raise ValueError("ManningN_MaterialID must be an integer")
    
    #The name of the Manning's n zone whose n value is changes in the Monte Carlo simulations. 
    ManningN_MaterialName = "None"
    if 'ManningN_MaterialName' in run_specs:
        ManningN_MaterialName = run_specs['ManningN_MaterialName']
    
    #The ID of the inlet boundary condition (1-based)
    Q_bc_ID = -1
    if 'Q_bc_ID' in run_specs:
        Q_bc_ID = run_specs['Q_bc_ID']
    
    #The ID of the outlet boundary condition (1-based)
    WSE_bc_ID = -1
    if 'WSE_bc_ID' in run_specs:
        WSE_bc_ID = run_specs['WSE_bc_ID']
    
    #Whether to delete the Monte Carlo cases after simulation is done
    bDeleteCaseDir = run_specs['bDeleteCaseDir']

    #Whether to run the Monte Carlo simulations in parallel
    bParallel = run_specs['bParallel']
    
    #The number of cores to use for the Monte Carlo simulations
    nProcess = run_specs['nProcess']

    if bParallel:
        print("Running Monte Carlo simulations in parallel with", nProcess, "processes out of ", multiprocessing.cpu_count(), " cores available...")
    else:
        print("Running Monte Carlo simulations in serial ...")

    #Get the system name: Windows or Linux
    system_name = platform.system()

    #The control file name for the base case    
    if system_name == "Windows":
        srhcontrol_file = case_name+".srhhydro"
    elif system_name == "Linux":
        srhcontrol_file = case_name+"_SIF.dat"
    else:
        raise ValueError("Unsupported operating system: " + system_name)
    
    #load saved parameter values from file
    samples = np.genfromtxt(sampled_parameters_file, delimiter=' ', names=True)
    #print("samples = ", samples)

    # Access a specific parameter's samples by column name:
    #manning_n_samples = samples['Manning_n']
    #Q_samples = samples['Q']
    #WSE_samples = samples['WSE']   

    #number of samples
    nSamples = samples.shape[0] 

    #The Monte Carlo simulations can be run in parallel or in serial.    
    if bParallel:
        Monte_Carlo_simulations_parallel(srhcontrol_file, samples, ManningN_MaterialID, ManningN_MaterialName, Q_bc_ID, WSE_bc_ID, system_name, nProcess=nProcess, bDeleteCaseDir=bDeleteCaseDir)
    else:
        Monte_Carlo_simulations_serial(srhcontrol_file, samples, ManningN_MaterialID, ManningN_MaterialName, Q_bc_ID, WSE_bc_ID, system_name, bDeleteCaseDir=bDeleteCaseDir)

    #record the end time
    end_time = time.time()
    
    #print the total time taken in hours
    print("Total time taken: ", (end_time - start_time)/3600, " hours")

    print("All done!")


