from setuptools import setup, find_packages

setup(
    name="hydronet",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "plotly>=5.13.0",
        "scikit-learn>=1.2.0",
        "vtk>=9.2.0",
        "xarray>=2023.1.0",
        "netCDF4>=1.6.0",
        "mpi4py>=3.1.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.0",
            "black>=23.3.0",
            "flake8>=6.0.0",
            "mypy>=1.3.0",
            "sphinx>=6.1.0",
            "sphinx-rtd-theme>=1.2.0",
        ],
    },
    author="Your Name",
    author_email="your.email@example.com",
    description="A deep learning framework for solving partial differential equations",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/HydroNet",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    python_requires=">=3.8",
) 